### PR TITLE
Answer questions w.r.t. References

### PR DESCRIPTION
**Pull request by BirgitBoss**
Added new section "Referencing"
with two questions
- [What is the relationship between text serialization of "Reference" and other serializations like json or xml?](#idr1)
- [When are two references considered to match?](#idr2)
- Is it possible to determine the semanticID of a submodel from an AAS Server or an AAS Repository Server without loading the actual submodel?(#idgh63)

Additionally updated links in AASBOK

editorial changes

### CODE REVIEW

**Comment by StenGruener** [comment]
@BirgitBoss could you please kindly check the removal of links, e.g., FAAAST, otherwise I am happy

**Comment by BirgitBoss** [comment]
FAAST is now also part of Eclipse Digital Twin, so it should be fine

**Comment by StenGruener** [comment]
@BirgitBoss  and others which werre removed? 
https://aas-test.ifak.eu/login/?next=/
https://github.com/rwth-iat/aas_manager

**Comment by BirgitBoss** [comment]
It is part of admin-Shell-io:  either you really explain every single project (and maintain it) or you - and this is the approach- I recommend and did - just reference the two major open source organizations : eclipse dt and admin-Shell-io

**Comment by StenGruener** [comment]
@BirgitBoss thanks Birgit, merging in

**Pull request merged**
